#ifndef CMD_COMMON_H
#define CMD_COMMON_H

DECLES_BEGIN

#define PACKAGE_HEAD 0x7e
#define PACKAGE_END 0x7e

#define DIAG_AUTOTEST_F  0x46
#define DIAG_BOOT_MAIN_CMD 0xfe
#define DIAG_BOOT_SUB_CMD_1 0x01
#define DIAG_BOOT_SUB_CMD_2 0x0b

typedef enum
{
	AUTOTEST_VERSIONINFO = 0,
	AUTOTEST_BACKLIGHT,
	AUTOTEST_ECHOLOOP,
	AUTOTEST_ECHOLOOP_2,
	AUTOTEST_TP,
	AUTOTEST_KEYPRESS,
	AUTOTEST_VIBRATOR,
	AUTOTEST_RECEIVE,
	AUTOTEST_LCD,
	AUTOTEST_RING,//09
	AUTOTEST_HEADSET,
	AUTOTEST_RTC,
	AUTOTEST_MEMORYCARD,
	AUTOTEST_LED,
	AUTOTEST_BLUETOOTH,
	AUTOTEST_FM,
	AUTOTEST_CAMERA,//0x10
	AUTOTEST_CAMERA1,
	AUTOTEST_PHONECALL,
	AUTOTEST_MSENSOR,
	AUTOTEST_CFT,
	AUTOTEST_GSENSOR,
	AUTOTEST_FLASHLIGHT,
	AUTOTEST_P_L_SENSOR,
	AUTOTEST_CHARGE,
	AUTOTEST_WIFI,//0x19
	AUTOTEST_SIM,
	AUTOTEST_KEYBL,
	AUTOTEST_OVER,
	//other aux cmd
	AUTOTEST_GPS,
	AUTOTEST_TRACE,
	AUTOTEST_OK,
	AUTOTEST_GETOPTIONFLAGS = 0xff,
	AUTOTEST_INVALID
}AUTOTEST_E;

typedef enum
{
	AUTOTEST_RET_PASS = 0,
	AUTOTEST_RET_FAIL,
	AUTOTEST_RET_DONE,
	AUTOTEST_RET_NOTSUPPORT,
	AUTOTEST_RET_TIMEOUT,
	AUTOTEST_RET_CMD,
	AUTOTEST_RET_STEP1,
	AUTOTEST_RET_STEP2,
	AUTOTEST_RET_STEP3
}AUTOTEST_RET_E;

DECLES_END
#endif // CMD_COMMON_H
